### ISSUE TITLE
Idea: handle errors the stream way

### ISSUE THREAD

**Issue by tomek-he-him** [brycebaril/through2-reduce#3]
Wondering about the performance hit though.

**Comment by tomek-he-him** [comment]
Sorry, that got published by mistake. Here's what I meant:

Hi there! Thank you for a great piece of code. I was delighted with the idea of reducing streams so idiomatically.

The problem arises when I need to handle errors though. I wanted to use _through2-reduce_ in a [gulp](http://gulpjs.com/) task. It's in fact nothing but a node stream. And as such it shouldn't throw errors – otherwise you get stack traces hunreds of calls deep.

The right way to handle an error in _through2_ is to pass it as the first argument of `callback`. That's of course impossible in _through2-reduce_ as there's no `callback` argument. Perhaps we could simply catch errors from `fn` and issue an `error` event?

Wondering about the performance hit though.

**Comment by brycebaril** [comment]
Great idea! The performance impact shouldn't be much, given in most cases the stream chunk handling is done asynchronously. Generally the stream overhead and event loop overhead should trivialize the cost of this try/catch.

I've gone ahead and published this as version 0.3.0 -- please take a look!

I added two tests, one where instead of throwing you can just "emit" an error in the reducing function. This worked prior this patch, but didn't have a test.

Also I added the try/catch around the reducer which then does what you suggested.

In both cases the correct way to handle the errors is just to capture the "error" event off the reducing stream, which means it maintains the stream API.

Take a look at the tests for implementation and let me know what you think!

**Comment by tomek-he-him** [comment]
I've looked at the tests and used it in the wild – works like a charm! Thanks a lot for the quick reaction.

Now working with streams actually starts being fun for me :)
